[32m[?7lgc.l:41     [0m (eval type)
[?7h[32m[?7lgc.l:41     [0m (array-at %structure-sizes (eval type))
[?7h[32m[?7lgc.l:41     [0m (* 4 (array-at %structure-sizes (eval type)))
[?7h[32m[?7lboot2.l:1052[0m (eval expr)
[?7h[32m[?7lboot2.l:1052[0m (let ((result (eval expr))) (and (> (verbose) 1) (println "=> " result)) result)
[?7h[32m[?7lboot2.l:1068[0m (pval expr)
[?7h[32m[?7lboot2.l:1068[0m (let ((expr (car _list_))) (pval expr))
[?7h[32m[?7lboot2.l:1068[0m (while _list_ (let ((expr (car _list_))) (pval expr)) (set _list_ (cdr _list_)))
[?7h[32m[?7lboot2.l:1068[0m (let ((_list_ exps)) (while _list_ (let ((expr (car _list_))) (pval expr)) (set _list_ (cdr _list_))))
[?7h[32m[?7lboot2.l:1066[0m (let ((exps (find-and-read name))) (or exps (error "file not found or empty: " name)) (let ((_list_ exps)) (while _list_ (let ((expr (car _list_))) (pval expr)) (set _list_ (cdr _list_)))))
[?7h[32m[?7lmaru.k:299  [0m (load (let ((_list_ *arguments*)) (let ((_head_ (car _list_))) (let () (set *arguments* (cdr _list_)) _head_))))
[?7h[32m[?7lmaru.k:298  [0m (while *arguments* (load (let ((_list_ *arguments*)) (let ((_head_ (car _list_))) (let () (set *arguments* (cdr _list_)) _head_)))))
[?7h