Loading threaded C compiler for evalm...
emit-c-threaded-fixed.l loaded
[32m[?7l...         [0m c-gen-expr-to-threaded-complete
[?7h[32m[?7lemit-c-threaded-complete.l:140[0m (c-gen-expr-to-threaded-complete val-expr "thread_cont")
[?7h[32m[?7lemit-c-threaded-complete.l:140[0m (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");"))
[?7h[32m[?7lemit-c-threaded-complete.l:139[0m (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);")))
[?7h[32m[?7lemit-c-threaded-complete.l:137[0m (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))
[?7h[32m[?7lemit-c-threaded-complete.l:136[0m (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);")))))
[?7h[32m[?7lemit-c-threaded-complete.l:136[0m (while _list_ (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))) (set _list_ (cdr _list_)))
[?7h[32m[?7lemit-c-threaded-complete.l:136[0m (let ((_list_ bindings)) (while _list_ (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))) (set _list_ (cdr _list_))))
[?7h[32m[?7lemit-c-threaded-complete.l:127[0m (let ((thread-name (c-fresh-thread))) (print "oop ") (print thread-name) (println "(thread_context *ctx) {") (set *c-indent-level* 1) (c-emit-line "Env *saved_env = ctx->env;") (c-emit-line "ctx->env = env_extend(ctx->env);") (let ((_list_ bindings)) (while _list_ (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))) (set _list_ (cdr _list_)))) (c-emit "oop result = ") (print body-thread) (println "(ctx);") (c-emit-line "ctx->env = saved_env;") (c-emit-line "ctx->acc = result;") (c-emit "return ") (print next) (println "(ctx);") (set *c-indent-level* 0) (println "}") (println) thread-name)
[?7h[32m[?7lemit-c-threaded-complete.l:125[0m (lambda (bindings body-thread next) "Generate threaded code for let with proper environment" (let ((thread-name (c-fresh-thread))) (print "oop ") (print thread-name) (println "(thread_context *ctx) {") (set *c-indent-level* 1) (c-emit-line "Env *saved_env = ctx->env;") (c-emit-line "ctx->env = env_extend(ctx->env);") (let ((_list_ bindings)) (while _list_ (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))) (set _list_ (cdr _list_)))) (c-emit "oop result = ") (print body-thread) (println "(ctx);") (c-emit-line "ctx->env = saved_env;") (c-emit-line "ctx->acc = result;") (c-emit "return ") (print next) (println "(ctx);") (set *c-indent-level* 0) (println "}") (println) thread-name))
[?7h[32m[?7lemit-c-threaded-complete.l:125[0m (define c-gen-threaded-let (lambda (bindings body-thread next) "Generate threaded code for let with proper environment" (let ((thread-name (c-fresh-thread))) (print "oop ") (print thread-name) (println "(thread_context *ctx) {") (set *c-indent-level* 1) (c-emit-line "Env *saved_env = ctx->env;") (c-emit-line "ctx->env = env_extend(ctx->env);") (let ((_list_ bindings)) (while _list_ (let ((binding (car _list_))) (let ((var (car binding)) (val-expr (cadr binding))) (if (pair? val-expr) (let ((val-thread (c-gen-expr-to-threaded-complete val-expr "thread_cont"))) (c-emit "oop val_") (print var) (print " = ") (print val-thread) (println "(ctx);") (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), val_") (print var) (println ");")) (if (long? val-expr) (progn (c-emit "env_define(ctx->env, intern(\"") (print var) (print "\"), LONG(") (print val-expr) (println "));")) (c-emit "env_define(ctx->env, intern(\"") (print var) (println "\"), nil);"))))) (set _list_ (cdr _list_)))) (c-emit "oop result = ") (print body-thread) (println "(ctx);") (c-emit-line "ctx->env = saved_env;") (c-emit-line "ctx->acc = result;") (c-emit "return ") (print next) (println "(ctx);") (set *c-indent-level* 0) (println "}") (println) thread-name)))
[?7h[32m[?7lboot.l:996                    [0m (eval expr)
[?7h[32m[?7lboot.l:996                    [0m (Fixed<let> ((result (eval expr))) (Fixed<and> (> (verbose) 1) (println "=> " result)) result)
[?7h[32m[?7lboot.l:1007                   [0m (pval expr)
[?7h[32m[?7lboot.l:1007                   [0m (Fixed<let> ((expr (car _list_))) (pval expr))
[?7h[32m[?7lboot.l:1007                   [0m (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))
[?7h[32m[?7lboot.l:1007                   [0m (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_))))
[?7h[32m[?7lboot.l:1005                   [0m (Fixed<let> ((exps (find-and-read name))) (Fixed<or> exps (error "file not found or empty: " name)) (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))))
[?7h[32m[?7lcompile-evalm-threaded.l:8    [0m (load "emit-c-threaded-complete.l")
[?7h