Testing working threaded C compiler...
emit-c-threaded-fixed.l loaded
emit-c-threaded-working.l loaded

=== Generating C code for (+ 40 2) ===
/* Generated by Threaded C Compiler with Forward Declarations */
#include <stdio.h>
#include <stdlib.h>

typedef union Object *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

typedef struct {
    oop stack[1024];
    oop *sp;
    oop acc;
} thread_context;

/* Forward declarations */

error: cannot apply: ()
[32m[?7lemit-c-threaded-working.l:127[0m (reverse *all-threads*)
[?7h[32m[?7lemit-c-threaded-working.l:127[0m (Fixed<let> ((threads (reverse *all-threads*))) (Fixed<while> threads (print "oop ") (print (car threads)) (println "(thread_context *ctx);") (Fixed<set> threads (cdr threads))))
[?7h[32m[?7lemit-c-threaded-working.l:116[0m (Fixed<let> ((main-thread (Fixed<if> (Fixed<and> (pair? expr) (= (car expr) (Fixed<quote> +))) (c-gen-threaded-binop-fwd "+" (cadr expr) (caddr expr) ret-thread) (Fixed<if> (long? expr) (c-gen-threaded-literal-fwd expr ret-thread) (error "Unsupported expression"))))) (println "/* Forward declarations */") (Fixed<let> ((threads (reverse *all-threads*))) (Fixed<while> threads (print "oop ") (print (car threads)) (println "(thread_context *ctx);") (Fixed<set> threads (cdr threads)))) (println) (println "/* Thread definitions */") (Fixed<let> ((defs (reverse *thread-definitions*))) (Fixed<while> defs (print-list (car defs)) (Fixed<set> defs (cdr defs)))) (println "int main() {") (println "    thread_context ctx = {0};") (println "    ctx.sp = ctx.stack;") (print "    oop result = ") (print main-thread) (println "(&ctx);") (println "    printf(\"Result: %ld\\n\", getLong(result));") (println "    return 0;") (println "}"))
[?7h[32m[?7lemit-c-threaded-working.l:116[0m (Fixed<let> ((ret-thread (c-gen-threaded-return-fwd))) (Fixed<let> ((main-thread (Fixed<if> (Fixed<and> (pair? expr) (= (car expr) (Fixed<quote> +))) (c-gen-threaded-binop-fwd "+" (cadr expr) (caddr expr) ret-thread) (Fixed<if> (long? expr) (c-gen-threaded-literal-fwd expr ret-thread) (error "Unsupported expression"))))) (println "/* Forward declarations */") (Fixed<let> ((threads (reverse *all-threads*))) (Fixed<while> threads (print "oop ") (print (car threads)) (println "(thread_context *ctx);") (Fixed<set> threads (cdr threads)))) (println) (println "/* Thread definitions */") (Fixed<let> ((defs (reverse *thread-definitions*))) (Fixed<while> defs (print-list (car defs)) (Fixed<set> defs (cdr defs)))) (println "int main() {") (println "    thread_context ctx = {0};") (println "    ctx.sp = ctx.stack;") (print "    oop result = ") (print main-thread) (println "(&ctx);") (println "    printf(\"Result: %ld\\n\", getLong(result));") (println "    return 0;") (println "}")))
[?7h[32m[?7ltest-working-compiler.l:11   [0m (compile-with-forwards (Fixed<quote> (+ 40 2)))
[?7h