Testing emit-c-threaded.l...
emit-c-threaded.l loaded

=== Test 1: Simple Threaded Function ===
/* Generated by Maru Threaded C Backend */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef union Object *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

/* Threaded execution context */
typedef struct {
    oop stack[1024];   /* Value stack */
    oop *sp;           /* Stack pointer */
    oop locals[256];   /* Local variables */
    oop acc;           /* Accumulator */
} thread_context;

typedef oop (*thread_func)(thread_context *ctx);

/* Stack operations */
#define PUSH(ctx, val) (*((ctx)->sp++) = (val))
#define POP(ctx) (*(--(ctx)->sp))
#define PEEK(ctx) (*((ctx)->sp - 1))

oop thread_1(thread_context *ctx) {
    return ctx->acc;
}

oop thread_2(thread_context *ctx) {
[32m[?7lcore/compiler/emit-c-threaded.l:65[0m (concat-string "LONG(" (long->string value) ")")
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:64[0m (Fixed<if> (long? value) (concat-string "LONG(" (long->string value) ")") "nil")
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:64[0m (concat-string "ctx->acc = " (Fixed<if> (long? value) (concat-string "LONG(" (long->string value) ")") "nil") ";")
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:64[0m (c-emit-line (concat-string "ctx->acc = " (Fixed<if> (long? value) (concat-string "LONG(" (long->string value) ")") "nil") ";"))
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:61[0m (Fixed<let> ((thread-name (c-fresh-thread))) (println "oop " thread-name "(thread_context *ctx) {") (Fixed<set> *c-indent-level* 1) (c-emit-line (concat-string "ctx->acc = " (Fixed<if> (long? value) (concat-string "LONG(" (long->string value) ")") "nil") ";")) (c-emit-line (concat-string "return " next "(ctx);")) (Fixed<set> *c-indent-level* 0) (println "}") (println) thread-name)
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:146[0m (c-gen-threaded-literal 42 ret-thread)
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:146[0m (Fixed<set> thread42 (c-gen-threaded-literal 42 ret-thread))
[?7h[32m[?7lcore/compiler/emit-c-threaded.l:140[0m (Fixed<let> ((ret-thread (c-gen-threaded-return)) (thread42 ()) (thread40 ()) (add-thread ())) (Fixed<set> thread42 (c-gen-threaded-literal 42 ret-thread)) (Fixed<set> thread40 (c-gen-threaded-literal 40 thread42)) (Fixed<set> add-thread (c-gen-threaded-binop "+" "thread_2" "thread_1" ret-thread)) (println "oop add_threaded(oop a, oop b) {") (Fixed<set> *c-indent-level* 1) (c-emit-line "thread_context ctx = {0};") (c-emit-line "ctx.sp = ctx.stack;") (c-emit-line "PUSH(&ctx, a);") (c-emit-line "PUSH(&ctx, b);") (c-emit-line (concat-string "return " add-thread "(&ctx);")) (Fixed<set> *c-indent-level* 0) (println "}") (println) (println "int main() {") (Fixed<set> *c-indent-level* 1) (c-emit-line "oop result = add_threaded(LONG(40), LONG(2));") (c-emit-line "printf(\"Threaded result: %ld\\n\", getLong(result));") (c-emit-line "return 0;") (Fixed<set> *c-indent-level* 0) (println "}"))
[?7h[32m[?7ltest-emit-c-threaded.l:10          [0m (generate-threaded-function)
[?7h