/* Generated by Maru C backend */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef union Object *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

int main() {
  oop _acc = nil;
_acc = LONG(42);
_acc = LONG(-getLong(_acc));
  printf("Result: %ld\n", getLong(_acc));
  return 0;
}

