
error: undefined variable: compiler
[32m[?7l...         [0m compiler
[?7h[32m[?7lemit-c-minimal.l:215[0m (compiler 0)
[?7h[32m[?7lemit-c-minimal.l:214[0m (let ((comp (compiler 0))) (let ((index (array-length vars))) (while (<= 0 (set index (- index 1))) (let ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (if (and (= *emit-backend* (quote c)) (= <expr> (type-of value))) (let ((defn (oop-at (%typecheck <expr> value) 1))) (let ((body (cddr defn))) (let ((comp2 (compiler (+ 1 (<compiler>-level comp))))) (let ((main (= (quote main) name))) (print "long " name "(") (let ((params (cadr defn)) (first 1)) (let ((_list_ params)) (while _list_ (let ((param (car _list_))) (and (not first) (print ", ")) (set first ()) (print "long param" (list-length params))) (set _list_ (cdr _list_))))) (println ") {") (c-indent) (println "long _eax = 0;") (c-indent) (println "_eax = 42;") (c-indent) (println "return _eax;") (println "}") (println))))) (gen-definition value name comp))))))
[?7h[32m[?7lemit-c-minimal.l:214[0m (let ((vars (oop-at (%typecheck <env> env) 3))) (let ((comp (compiler 0))) (let ((index (array-length vars))) (while (<= 0 (set index (- index 1))) (let ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (if (and (= *emit-backend* (quote c)) (= <expr> (type-of value))) (let ((defn (oop-at (%typecheck <expr> value) 1))) (let ((body (cddr defn))) (let ((comp2 (compiler (+ 1 (<compiler>-level comp))))) (let ((main (= (quote main) name))) (print "long " name "(") (let ((params (cadr defn)) (first 1)) (let ((_list_ params)) (while _list_ (let ((param (car _list_))) (and (not first) (print ", ")) (set first ()) (print "long param" (list-length params))) (set _list_ (cdr _list_))))) (println ") {") (c-indent) (println "long _eax = 0;") (c-indent) (println "_eax = 42;") (c-indent) (println "return _eax;") (println "}") (println))))) (gen-definition value name comp)))))))
[?7h[32m[?7lemit-c-minimal.l:206[0m (lambda (env) (println "#include <stdio.h>") (println "#include <stdlib.h>") (println "#include <string.h>") (println) (let ((vars (oop-at (%typecheck <env> env) 3))) (let ((comp (compiler 0))) (let ((index (array-length vars))) (while (<= 0 (set index (- index 1))) (let ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (if (and (= *emit-backend* (quote c)) (= <expr> (type-of value))) (let ((defn (oop-at (%typecheck <expr> value) 1))) (let ((body (cddr defn))) (let ((comp2 (compiler (+ 1 (<compiler>-level comp))))) (let ((main (= (quote main) name))) (print "long " name "(") (let ((params (cadr defn)) (first 1)) (let ((_list_ params)) (while _list_ (let ((param (car _list_))) (and (not first) (print ", ")) (set first ()) (print "long param" (list-length params))) (set _list_ (cdr _list_))))) (println ") {") (c-indent) (println "long _eax = 0;") (c-indent) (println "_eax = 42;") (c-indent) (println "return _eax;") (println "}") (println))))) (gen-definition value name comp))))))))
[?7h[32m[?7lemit-c-minimal.l:206[0m (define gen-env-c (lambda (env) (println "#include <stdio.h>") (println "#include <stdlib.h>") (println "#include <string.h>") (println) (let ((vars (oop-at (%typecheck <env> env) 3))) (let ((comp (compiler 0))) (let ((index (array-length vars))) (while (<= 0 (set index (- index 1))) (let ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (if (and (= *emit-backend* (quote c)) (= <expr> (type-of value))) (let ((defn (oop-at (%typecheck <expr> value) 1))) (let ((body (cddr defn))) (let ((comp2 (compiler (+ 1 (<compiler>-level comp))))) (let ((main (= (quote main) name))) (print "long " name "(") (let ((params (cadr defn)) (first 1)) (let ((_list_ params)) (while _list_ (let ((param (car _list_))) (and (not first) (print ", ")) (set first ()) (print "long param" (list-length params))) (set _list_ (cdr _list_))))) (println ") {") (c-indent) (println "long _eax = 0;") (c-indent) (println "_eax = 42;") (c-indent) (println "return _eax;") (println "}") (println))))) (gen-definition value name comp)))))))))
[?7h[32m[?7lboot.l:996          [0m (eval expr)
[?7h[32m[?7lboot.l:996          [0m (Fixed<let> ((result (eval expr))) (Fixed<and> (> (verbose) 1) (println "=> " result)) result)
[?7h[32m[?7lboot.l:1007         [0m (pval expr)
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((expr (car _list_))) (pval expr))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_))))
[?7h[32m[?7lboot.l:1005         [0m (Fixed<let> ((exps (find-and-read name))) (Fixed<or> exps (error "file not found or empty: " name)) (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))))
[?7h[32m[?7lboot.l:1015         [0m (load name)
[?7h[32m[?7lboot.l:1013         [0m (Fixed<let> () (Fixed<set> *loaded* (cons name *loaded*)) (load name))
[?7h[32m[?7lboot.l:1012         [0m (Fixed<or> (member? name *loaded*) (Fixed<let> () (Fixed<set> *loaded* (cons name *loaded*)) (load name)))
[?7h[32m[?7ltest-c-minimal.l:10 [0m (require "emit-c-minimal.l")
[?7h