=== Evalm-Style Compilation Test ===
/* Generated by Maru Threaded C Backend */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef union Object *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

/* Threaded execution context */
typedef struct {
    oop stack[1024];   /* Value stack */
    oop *sp;           /* Stack pointer */
    oop locals[256];   /* Local variables */
    oop acc;           /* Accumulator */
} thread_context;

typedef oop (*thread_func)(thread_context *ctx);

/* Stack operations */
#define PUSH(ctx, val) (*((ctx)->sp++) = (val))
#define POP(ctx) (*(--(ctx)->sp))
#define PEEK(ctx) (*((ctx)->sp - 1))

/* Runtime support for evalm */

typedef struct Env {
    struct Env *parent;
    oop bindings[256];
    char *names[256];
    int count;
} Env;

typedef struct {
    thread_func func;
    Env *env;
} Closure;

oop lookup_variable(char *name, thread_context *ctx) {
    /* Simplified variable lookup */
    return nil;
}

void bind_variable(char *name, oop value, thread_context *ctx) {
    /* Simplified variable binding */
}

void push_env_frame(thread_context *ctx) {
    /* Push new environment frame */
}

void pop_env_frame(thread_context *ctx) {
    /* Pop environment frame */
}

oop make_closure(thread_func func, thread_context *ctx) {
    /* Create closure */
    return nil;
}

oop apply_function(oop func, oop arg0, thread_context *ctx) {
    /* Apply function */
    return nil;
}

oop thread_ret(thread_context *ctx) {
    return ctx->acc;
}


[31;1merror: Complex arithmetic not yet supported[m
[32m[?7lboot.l:24   [0m (abort)
[?7h[32m[?7lemit-c-threaded-evalm.l:126[0m (error "Complex arithmetic not yet supported")
[?7h[32m[?7lemit-c-threaded-evalm.l:124[0m (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported"))
[?7h[32m[?7lemit-c-threaded-evalm.l:122[0m (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))
[?7h[32m[?7lemit-c-threaded-evalm.l:122[0m (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported"))))
[?7h[32m[?7lemit-c-threaded-evalm.l:120[0m (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))
[?7h[32m[?7lemit-c-threaded-evalm.l:119[0m (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread))))))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type"))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (symbol? expr) (c-gen-threaded-variable expr next-thread) (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type")))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (long? expr) (c-gen-threaded-literal expr next-thread) (Fixed<if> (symbol? expr) (c-gen-threaded-variable expr next-thread) (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type"))))
[?7h[32m[?7lemit-c-threaded-evalm.l:131[0m (c-gen-expr-to-threaded-extended body "thread_ret")
[?7h[32m[?7lemit-c-threaded-evalm.l:131[0m (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))
[?7h[32m[?7lemit-c-threaded-evalm.l:129[0m (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread)))
[?7h[32m[?7lemit-c-threaded-evalm.l:120[0m (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread))))
[?7h[32m[?7lemit-c-threaded-evalm.l:120[0m (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))
[?7h[32m[?7lemit-c-threaded-evalm.l:119[0m (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread))))))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type"))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (symbol? expr) (c-gen-threaded-variable expr next-thread) (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type")))
[?7h[32m[?7lemit-c-threaded-evalm.l:111[0m (Fixed<if> (long? expr) (c-gen-threaded-literal expr next-thread) (Fixed<if> (symbol? expr) (c-gen-threaded-variable expr next-thread) (Fixed<if> (pair? expr) (Fixed<let> ((op (car expr))) (Fixed<if> (= op (Fixed<quote> +)) (Fixed<let> ((left (cadr expr))) (Fixed<let> ((right (caddr expr))) (Fixed<if> (Fixed<and> (long? left) (long? right)) (c-gen-threaded-binop "+" left right next-thread) (error "Complex arithmetic not yet supported")))) (Fixed<if> (= op (Fixed<quote> let)) (Fixed<let> ((bindings (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-let bindings body-thread next-thread))) (Fixed<if> (= op (Fixed<quote> lambda)) (Fixed<let> ((params (cadr expr)) (body (caddr expr))) (Fixed<let> ((body-thread (c-gen-expr-to-threaded-extended body "thread_ret"))) (c-gen-threaded-lambda params body-thread next-thread))) (Fixed<let> ((func-thread (c-gen-expr-to-threaded-extended (car expr) "thread_cont")) (arg-threads (map (Fixed<lambda> (arg) (c-gen-expr-to-threaded-extended arg "thread_cont")) (cdr expr)))) (c-gen-threaded-funcall func-thread arg-threads next-thread)))))) (error "Unsupported expression type"))))
[?7h[32m[?7lemit-c-threaded-evalm.l:211[0m (c-gen-expr-to-threaded-extended expr "thread_ret")
[?7h[32m[?7lemit-c-threaded-evalm.l:210[0m (Fixed<let> ((main-thread (c-gen-expr-to-threaded-extended expr "thread_ret"))) (println "/* Test expression: (let ((x 10)) (+ x 32)) */") (println "oop eval_let_expr() {") (Fixed<set> *c-indent-level* 1) (c-emit-line "thread_context ctx = {0};") (c-emit-line "ctx.sp = ctx.stack;") (c-emit "return ") (print main-thread) (println "(&ctx);") (Fixed<set> *c-indent-level* 0) (println "}") (println) (println "int main() {") (Fixed<set> *c-indent-level* 1) (c-emit-line "printf(\"Evalm-style threaded compilation test\\n\");") (c-emit-line "/* Would execute: (let ((x 10)) (+ x 32)) */") (c-emit-line "return 0;") (Fixed<set> *c-indent-level* 0) (println "}"))
[?7h[32m[?7lemit-c-threaded-evalm.l:210[0m (Fixed<let> ((expr (Fixed<quote> (let ((x 10)) (+ x 32))))) (Fixed<let> ((main-thread (c-gen-expr-to-threaded-extended expr "thread_ret"))) (println "/* Test expression: (let ((x 10)) (+ x 32)) */") (println "oop eval_let_expr() {") (Fixed<set> *c-indent-level* 1) (c-emit-line "thread_context ctx = {0};") (c-emit-line "ctx.sp = ctx.stack;") (c-emit "return ") (print main-thread) (println "(&ctx);") (Fixed<set> *c-indent-level* 0) (println "}") (println) (println "int main() {") (Fixed<set> *c-indent-level* 1) (c-emit-line "printf(\"Evalm-style threaded compilation test\\n\");") (c-emit-line "/* Would execute: (let ((x 10)) (+ x 32)) */") (c-emit-line "return 0;") (Fixed<set> *c-indent-level* 0) (println "}")))
[?7h[32m[?7ltest-emit-c-threaded-evalm.l:9[0m (test-evalm-compilation)
[?7h