#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Forward declarations */
long main();
long factorial();
long add();

/* defn main */
long main() {
  long _eax = 0;

emit: illegal instruction: (() ___L__1__test_2Dc_2Demit_2El__17)
[31;1merror: aborted[m
[32m[?7lboot.l:24   [0m (abort)
[?7h[32m[?7lemit.l:73   [0m (error "aborted")
[?7h[32m[?7lboot.l:707  [0m (apply default arguments)
[?7h[32m[?7lboot.l:706  [0m (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments))
[?7h[32m[?7lboot.l:705  [0m (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments)))
[?7h[32m[?7lboot.l:703  [0m (Fixed<if> (Fixed<and> method (not (array? method))) (apply method arguments) (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments))))
[?7h[32m[?7lboot.l:698  [0m (Fixed<let> ((method (oop-at (%typecheck <generic> self) 1)) (arg arguments)) (Fixed<while> arg (Fixed<set> method (array-at method (type-of (car arg)))) (Fixed<set> arg (cdr arg))) (Fixed<if> (Fixed<and> method (not (array? method))) (apply method arguments) (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments)))))
[?7h[32m[?7lemit-c.l:223[0m (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i))
[?7h[32m[?7lemit-c.l:222[0m (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))
[?7h[32m[?7lemit-c.l:222[0m (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1))))
[?7h[32m[?7lemit-c.l:190[0m (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";")))
[?7h[32m[?7lemit-c.l:190[0m (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";"))))
[?7h[32m[?7lemit-c.l:190[0m (Fixed<let> ((body (cddr defn))) (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";")))))
[?7h[32m[?7lemit-c.l:190[0m (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";"))))))
[?7h[32m[?7lemit-c.l:190[0m (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";")))))))
[?7h[32m[?7l...         [0m (Fixed<let> () (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";"))))))))
[?7h[32m[?7l...         [0m (Fixed<let> () (Fixed<let> () (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((comp (compiler (+ 1 (oop-at (%typecheck <compiler> ocomp) 0))))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (print "long " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "long _param_" (>> (oop-at (%typecheck <TI32> param) 0) 2))) (Fixed<set> _list_ (cdr _list_))))) (println ") {") (Fixed<set> *c-indent* 1) (c-indent) (println "long _eax = 0;") (Fixed<let> ((max-args (oop-at (%typecheck <compiler> comp) 3))) (Fixed<let> ((i 0) (_limit_ (>> max-args 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _arg_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((max-temps (oop-at (%typecheck <compiler> comp) 5))) (Fixed<let> ((i 0) (_limit_ (>> max-temps 2))) (Fixed<while> (< i _limit_) (c-indent) (println "long _tmp_" i " = 0;") (Fixed<set> i (+ i 1))))) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (Fixed<and> (oop-at (%typecheck <compiler> comp) 7) (Fixed<let> () (println (oop-at (%typecheck <compiler> comp) 7) ":") (c-indent))) (println "return _eax;") (Fixed<set> *c-indent* 0) (println "}") (println) (Fixed<or> main (println "long " name " = (long)" name ";")))))))))
[?7h[32m[?7lboot.l:517  [0m (apply (Fixed<or> (array-at (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (<selector>-inherit (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (oop-at (%typecheck <selector> self) 2)) arguments)
[?7h[32m[?7lemit-c.l:288[0m (gen-definition value name comp)
[?7h[32m[?7lemit-c.l:285[0m (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (println "/* defn " name " */") (gen-definition value name comp))
[?7h[32m[?7lemit-c.l:284[0m (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (println "/* defn " name " */") (gen-definition value name comp)))
[?7h[32m[?7lemit-c.l:281[0m (Fixed<let> ((index (array-length vars))) (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (println "/* defn " name " */") (gen-definition value name comp))))
[?7h[32m[?7lemit-c.l:281[0m (Fixed<let> ((comp (compiler 0))) (Fixed<let> ((index (array-length vars))) (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (println "/* defn " name " */") (gen-definition value name comp)))))
[?7h[32m[?7lemit-c.l:281[0m (Fixed<let> ((vars (oop-at (%typecheck <env> env) 3))) (Fixed<let> ((comp (compiler 0))) (Fixed<let> ((index (array-length vars))) (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (println "/* defn " name " */") (gen-definition value name comp))))))
[?7h[32m[?7lemit.l:605  [0m (gen-env env)
[?7h[32m[?7lemit.l:603  [0m (Fixed<let> ((env *globals*)) (Fixed<set> *globals* (oop-at (%typecheck <env> env) 0)) (gen-env env))
[?7h