Loading minimal threaded backend...
Loading successful!
Testing compile-threaded:
/* Threaded C Code Generated by Maru */
#include <stdio.h>
#include <stdlib.h>

int main() {
    printf("Result: %ld\n", 42);
    return 0;
}
