
error: undefined variable: use-c-backend
[32m[?7l...         [0m use-c-backend
[?7h[32m[?7lcore/compiler/emit.l:496[0m (use-c-backend)
[?7h[32m[?7lcore/compiler/emit.l:495[0m (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))
[?7h[32m[?7lcore/compiler/emit.l:494[0m (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend))))
[?7h[32m[?7lcore/compiler/emit.l:493[0m (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))
[?7h[32m[?7lcore/compiler/emit.l:492[0m (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend))))))
[?7h[32m[?7lcore/compiler/emit.l:491[0m (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))
[?7h[32m[?7lcore/compiler/emit.l:490[0m (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend))))))))
[?7h[32m[?7lcore/compiler/emit.l:489[0m (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))))
[?7h[32m[?7lcore/compiler/emit.l:488[0m (let ((extern-binding (assq (quote extern) *globals*))) (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend))))))))))
[?7h[32m[?7lcore/compiler/emit.l:486[0m (let ((env *globals*)) (let ((extern-binding (assq (quote extern) *globals*))) (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))))) (set *globals* (oop-at (%typecheck <env> env) 0)) (gen-env env))
[?7h[32m[?7lcore/compiler/emit.l:486[0m (lambda (*env*) (let ((env *globals*)) (let ((extern-binding (assq (quote extern) *globals*))) (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))))) (set *globals* (oop-at (%typecheck <env> env) 0)) (gen-env env)))
[?7h[32m[?7lcore/compiler/emit.l:486[0m (form (lambda (*env*) (let ((env *globals*)) (let ((extern-binding (assq (quote extern) *globals*))) (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))))) (set *globals* (oop-at (%typecheck <env> env) 0)) (gen-env env))))
[?7h[32m[?7lcore/compiler/emit.l:486[0m (define compile-end (form (lambda (*env*) (let ((env *globals*)) (let ((extern-binding (assq (quote extern) *globals*))) (if extern-binding (let ((extern-fn (cdr extern-binding))) (if extern-fn (let ((getenv (extern-fn (quote getenv)))) (let ((backend-name (getenv "MARU_EMIT_BACKEND"))) (if backend-name (if (= (string->symbol backend-name) (quote c)) (use-c-backend) (if (= (string->symbol backend-name) (quote arm64)) (use-arm64-backend) (use-c-backend)))))))))) (set *globals* (oop-at (%typecheck <env> env) 0)) (gen-env env)))))
[?7h