[32m[?7l...         [0m nil
[?7h[32m[?7lsource-tracking.l:72[0m (if (pair? obj) (oop-at (%typecheck <pair> obj) 2) nil)
[?7h[32m[?7lsource-tracking.l:70[0m (lambda (obj) "Extract source location from an object" (if (pair? obj) (oop-at (%typecheck <pair> obj) 2) nil))
[?7h[32m[?7lsource-tracking.l:70[0m (define get-source-location (lambda (obj) "Extract source location from an object" (if (pair? obj) (oop-at (%typecheck <pair> obj) 2) nil)))
[?7h[32m[?7lboot.l:996          [0m (eval expr)
[?7h[32m[?7lboot.l:996          [0m (Fixed<let> ((result (eval expr))) (Fixed<and> (> (verbose) 1) (println "=> " result)) result)
[?7h[32m[?7lboot.l:1007         [0m (pval expr)
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((expr (car _list_))) (pval expr))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_))))
[?7h[32m[?7lboot.l:1005         [0m (Fixed<let> ((exps (find-and-read name))) (Fixed<or> exps (error "file not found or empty: " name)) (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))))
[?7h[32m[?7lemit-gc-c-debug.l:6 [0m (load "source-tracking.l")
[?7h[32m[?7lboot.l:996          [0m (eval expr)
[?7h[32m[?7lboot.l:996          [0m (Fixed<let> ((result (eval expr))) (Fixed<and> (> (verbose) 1) (println "=> " result)) result)
[?7h[32m[?7lboot.l:1007         [0m (pval expr)
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((expr (car _list_))) (pval expr))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))
[?7h[32m[?7lboot.l:1007         [0m (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_))))
[?7h[32m[?7lboot.l:1005         [0m (Fixed<let> ((exps (find-and-read name))) (Fixed<or> exps (error "file not found or empty: " name)) (Fixed<let> ((_list_ exps)) (Fixed<while> _list_ (Fixed<let> ((expr (car _list_))) (pval expr)) (Fixed<set> _list_ (cdr _list_)))))
[?7h[32m[?7ltest-source-tracking.l:4[0m (load "emit-gc-c-debug.l")
[?7h