emit-c-threaded.l loaded - Unified Threaded C Backend
=== Testing Basic Threaded Compilation ===
/* Threaded C Code Generated by Maru */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef void *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

typedef struct {
    oop stack[1024];    /* Value stack */
    oop *sp;            /* Stack pointer */
    oop locals[256];    /* Local variables */
    oop acc;            /* Accumulator */
} thread_context;

/* Runtime support functions */
oop lookup_var(const char *name, thread_context *ctx) {
    /* Variable lookup not implemented yet */
    return nil;
}

/* Forward declarations */
oop thread_1(thread_context *ctx);
oop thread_2(thread_context *ctx);

/* Thread implementations */
oop thread_1(thread_context *ctx) {
    return ctx->acc;
}

oop thread_2(thread_context *ctx) {
    ctx->acc = LONG(42);
    return thread_1(ctx);
}

int main() {
    thread_context ctx = {0};
    ctx.sp = ctx.stack;
    oop result = thread_2(&ctx);
    if (result) {
        printf("Result: %ld\n", getLong(result));
    } else {
        printf("Result: nil\n");
    }
    return 0;
}
