
error: undefined variable: *emit-backend*
[32m[?7l...         [0m *emit-backend*
[?7h[32m[?7lcore/compiler/emit.l:142[0m (= *emit-backend* (quote c))
[?7h[32m[?7lcore/compiler/emit.l:142[0m (if (= *emit-backend* (quote c)) (print (c-temp-name self)) (print (oop-at (%typecheck <TI32> self) 0) "(%esp)"))
[?7h[32m[?7l...                     [0m (let () (if (= *emit-backend* (quote c)) (print (c-temp-name self)) (print (oop-at (%typecheck <TI32> self) 0) "(%esp)")))
[?7h[32m[?7l...                     [0m (let () (let () (if (= *emit-backend* (quote c)) (print (c-temp-name self)) (print (oop-at (%typecheck <TI32> self) 0) "(%esp)"))))
[?7h[32m[?7l...                     [0m (lambda (self) (let () (let () (if (= *emit-backend* (quote c)) (print (c-temp-name self)) (print (oop-at (%typecheck <TI32> self) 0) "(%esp)")))))
[?7h[32m[?7lboot.l:552              [0m (eval (cons (Fixed<quote> lambda) (cons args (cons (cons (Fixed<quote> with-instance-accessors) (cons type body)) (Fixed<quote> ())))))
[?7h[32m[?7lboot.l:552              [0m (<selector>-add-method self type (eval (cons (Fixed<quote> lambda) (cons args (cons (cons (Fixed<quote> with-instance-accessors) (cons type body)) (Fixed<quote> ()))))))
[?7h[32m[?7lboot.l:517              [0m (apply (Fixed<or> (array-at (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (<selector>-inherit (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (oop-at (%typecheck <selector> self) 2)) arguments)
[?7h[32m[?7l...                     [0m (add-method do-print <TI32> (Fixed<quote> (self)) (Fixed<quote> ((if (= *emit-backend* (quote c)) (print (c-temp-name self)) (print (<TI32>-offset self) "(%esp)")))))
[?7h[32m[?7lcore/compiler/emit.l:60 [0m (eval (cons (Fixed<quote> define-method) (cons (Fixed<quote> do-print) (cons tname (cons (Fixed<quote> ()) printing)))))
[?7h[32m[?7lcore/compiler/emit.l:59 [0m (Fixed<if> printing (eval (cons (Fixed<quote> define-method) (cons (Fixed<quote> do-print) (cons tname (cons (Fixed<quote> ()) printing))))))
[?7h[32m[?7lcore/compiler/emit.l:52 [0m (Fixed<let> ((tname (string->symbol (concat-string "<" (concat-string sname ">"))))) (eval (cons (Fixed<quote> define-structure) (cons tname (cons fields (Fixed<quote> ()))))) (eval (cons (Fixed<quote> define-function) (cons name (cons fields (cons (cons (Fixed<quote> let) (cons (cons (cons (Fixed<quote> self) (cons (cons (Fixed<quote> new) (cons tname (Fixed<quote> ()))) (Fixed<quote> ()))) (Fixed<quote> ())) (concat-list (define-operand-make-setters tname fields) (cons (Fixed<quote> self) (Fixed<quote> ()))))) (Fixed<quote> ())))))) (Fixed<if> printing (eval (cons (Fixed<quote> define-method) (cons (Fixed<quote> do-print) (cons tname (cons (Fixed<quote> ()) printing)))))) tname)
[?7h[32m[?7lcore/compiler/emit.l:52 [0m (Fixed<let> ((sname (symbol->string name))) (Fixed<let> ((tname (string->symbol (concat-string "<" (concat-string sname ">"))))) (eval (cons (Fixed<quote> define-structure) (cons tname (cons fields (Fixed<quote> ()))))) (eval (cons (Fixed<quote> define-function) (cons name (cons fields (cons (cons (Fixed<quote> let) (cons (cons (cons (Fixed<quote> self) (cons (cons (Fixed<quote> new) (cons tname (Fixed<quote> ()))) (Fixed<quote> ()))) (Fixed<quote> ())) (concat-list (define-operand-make-setters tname fields) (cons (Fixed<quote> self) (Fixed<quote> ()))))) (Fixed<quote> ())))))) (Fixed<if> printing (eval (cons (Fixed<quote> define-method) (cons (Fixed<quote> do-print) (cons tname (cons (Fixed<quote> ()) printing)))))) tname))
[?7h