;;; Testing High-Fidelity GC C Emitter

/* Generated by Maru emit-gc-c.l - High-fidelity C with GC */

#define _ISOC99_SOURCE 1
#define _BSD_SOURCE 1

#include <stddef.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <signal.h>
#include <sys/types.h>
#include <errno.h>
#include <wchar.h>
#include <locale.h>
#include <math.h>
#if defined(__MACH__)
# include <ffi/ffi.h>
#else
# include <ffi.h>
#endif
#include <assert.h>

extern int isatty(int);

#if defined(WIN32)
# include <malloc.h>
# define swnprintf(BUF, SIZE, FMT, ARG) swprintf(BUF, FMT, ARG)
#else
# define swnprintf swprintf
#endif

#define TAG_INT 1
#define GC_APP_HEADER int type;
#define GC_SAVE 1

#include "gc.c"
#include "wcs.c"
#include "buffer.c"

union Object;
typedef union Object *oop;
typedef oop (*imp_t)(oop args, oop env);

#define nil ((oop)0)

enum { Undefined, Data, Long, Double, String, Symbol, Pair, _Array, Array, Expr, Form, Fixed, Subr, Variable, Env, Context };

struct Data { };
struct Long { long bits; };
struct Double { double bits; };
struct String { oop size; wchar_t *bits; };
struct Symbol { wchar_t *bits; };
struct Pair { oop head, tail, source; };
struct Array { oop size, _array; };
struct Expr { oop name, defn, ctx, profile; };
struct Form { oop function, symbol; };
struct Fixed { oop function; };
struct Subr { wchar_t *name; imp_t imp; void *sig; int profile; };
struct Variable { oop name, value, env, index, type; };
struct Env { oop parent, level, offset, bindings, stable; };
struct Context { oop home, env, bindings, callee, pc; };

union Object {
  struct Data Data;
  struct Long Long;
  struct Double Double;
  struct String String;
  struct Symbol Symbol;
  struct Pair Pair;
  struct Array Array;
  struct Expr Expr;
  struct Form Form;
  struct Fixed Fixed;
  struct Subr Subr;
  struct Variable Variable;
  struct Env Env;
  struct Context Context;
};

#define setType(OBJ, TYPE) (ptr2hdr(OBJ)->type= (TYPE))
#define getType(OBJ) ((OBJ) ? (((long)(OBJ) & 1) ? Long : ptr2hdr(OBJ)->type) : Undefined)
#define is(TYPE, OBJ) ((OBJ) && (TYPE == getType(OBJ)))
#define get(OBJ, TYPE, FIELD) ((OBJ)->TYPE.FIELD)
#define set(OBJ, TYPE, FIELD, VALUE) ((OBJ)->TYPE.FIELD= (VALUE))

#define newBits(TYPE) _newBits(TYPE, sizeof(struct TYPE))
#define newOops(TYPE) _newOops(TYPE, sizeof(struct TYPE))

static oop _newBits(int type, size_t size) { oop obj= GC_malloc_atomic(size); setType(obj, type); return obj; }
static oop _newOops(int type, size_t size) { oop obj= GC_malloc(size); setType(obj, type); return obj; }

static inline int isLong(oop x) { return (((long)x & 1) || Long == getType(x)); }
static inline oop newLong(long x) { if ((x ^ (x << 1)) < 0) { oop obj= newBits(Long); set(obj, Long,bits, x); return obj; } return ((oop)((x << 1) | 1)); }
static inline long getLong(oop x) { if ((long)x & 1) return (long)x >> 1; return get(x, Long,bits); }

/* Forward declarations for all global variables and functions */


[31;1merror: type check failed for field accessor: expected 64 <compiler> got 0 <undefined>[m
[32m[?7lboot.l:24   [0m (abort)
[?7h[32m[?7lboot.l:337  [0m (error "type check failed for field accessor: expected " type " " (array-at %type-names type) " got " (type-of object) " " (array-at %type-names (type-of object)))
[?7h[32m[?7lboot.l:335  [0m (Fixed<or> (= type (type-of object)) (inherits-from (type-of object) type) (error "type check failed for field accessor: expected " type " " (array-at %type-names type) " got " (type-of object) " " (array-at %type-names (type-of object))))
[?7h[32m[?7lemit.l:278  [0m (%typecheck <compiler> comp)
[?7h[32m[?7lemit.l:278  [0m (oop-at (%typecheck <compiler> comp) 1)
[?7h[32m[?7lemit.l:278  [0m (Fixed<let> ((i (oop-at (%typecheck <compiler> comp) 1))) (Fixed<let> ((t (TI32 i))) (set-oop-at (%typecheck <compiler> comp) 1 (+ i 4)) t))
[?7h[32m[?7lemit.l:537  [0m (new-param comp)
[?7h[32m[?7lemit.l:537  [0m (set-oop-at (%typecheck <variable> var) 1 (new-param comp))
[?7h[32m[?7lboot.l:207  [0m (function (car list) a)
[?7h[32m[?7lboot.l:207  [0m (Fixed<let> ((head (function (car list) a))) (cons head (map-with function (cdr list) a)))
[?7h[32m[?7lboot.l:206  [0m (Fixed<if> (pair? list) (Fixed<let> ((head (function (car list) a))) (cons head (map-with function (cdr list) a))))
[?7h[32m[?7lemit-gc-c.l:273[0m (map-with gen-param (cadr defn) comp)
[?7h[32m[?7lemit-gc-c.l:270[0m (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println))
[?7h[32m[?7lemit-gc-c.l:270[0m (Fixed<let> ((body (cddr defn))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println)))
[?7h[32m[?7lemit-gc-c.l:270[0m (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println))))
[?7h[32m[?7lemit-gc-c.l:270[0m (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println)))))
[?7h[32m[?7l...            [0m (Fixed<let> () (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println))))))
[?7h[32m[?7l...            [0m (Fixed<let> () (Fixed<let> () (Fixed<let> ((main (= (Fixed<quote> main) name))) (Fixed<let> ((defn (oop-at (%typecheck <expr> self) 1))) (Fixed<let> ((body (cddr defn))) (Fixed<let> ((params (map-with gen-param (cadr defn) comp))) (println "static oop " name "(") (Fixed<let> ((first 1)) (Fixed<let> ((_list_ params)) (Fixed<while> _list_ (Fixed<let> ((param (car _list_))) (Fixed<and> (not first) (print ", ")) (Fixed<set> first ()) (print "oop " (c-temp-name param))) (Fixed<set> _list_ (cdr _list_))))) (println ")") (c-begin-block) (c-indent) (println "oop _acc= nil;") (c-declare-temps comp) (c-declare-args comp) (Fixed<let> ((_list_ body)) (Fixed<while> _list_ (Fixed<let> ((e (car _list_))) (gen e comp)) (Fixed<set> _list_ (cdr _list_)))) (Fixed<let> ((i 0) (_limit_ (oop-at (%typecheck <compiler> comp) 9))) (Fixed<while> (< i _limit_) (apply emit (array-at (oop-at (%typecheck <compiler> comp) 8) i)) (Fixed<set> i (+ i 1)))) (c-unprotect-all) (c-indent) (println "return _acc;") (c-end-block) (println)))))))
[?7h[32m[?7lboot.l:517     [0m (apply (Fixed<or> (array-at (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (<selector>-inherit (oop-at (%typecheck <selector> self) 1) (type-of (car arguments))) (oop-at (%typecheck <selector> self) 2)) arguments)
[?7h[32m[?7lemit-gc-c.l:324[0m (gen-definition value name ())
[?7h[32m[?7lemit-gc-c.l:322[0m (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (gen-definition value name ()))
[?7h[32m[?7lemit-gc-c.l:321[0m (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (gen-definition value name ())))
[?7h[32m[?7lemit-gc-c.l:319[0m (Fixed<let> ((index (array-length vars))) (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (gen-definition value name ()))))
[?7h[32m[?7lemit-gc-c.l:319[0m (Fixed<let> ((vars (oop-at (%typecheck <env> env) 3))) (Fixed<let> ((index (array-length vars))) (Fixed<while> (<= 0 (Fixed<set> index (- index 1))) (Fixed<let> ((name (oop-at (%typecheck <variable> (array-at vars index)) 0)) (value (oop-at (%typecheck <variable> (array-at vars index)) 1))) (gen-definition value name ())))))
[?7h[32m[?7ltest-gc-c-emitter.l:32[0m (gen-env-gc-c test-env)
[?7h[32m[?7ltest-gc-c-emitter.l:26[0m (Fixed<let> ((test-env (environment ()))) (environment-define test-env (Fixed<quote> test-add) test-add) (environment-define test-env (Fixed<quote> test-pair-creation) test-pair-creation) (environment-define test-env (Fixed<quote> test-string-creation) test-string-creation) (gen-env-gc-c test-env) (println) (println "int main(int argc, char **argv)") (println "{") (println "  GC_init();") (println "  setlocale(LC_ALL, \"\");  /* UTF-8 support */") (println) (println "  /* Initialize global variables with GC protection */") (println "  initialize_globals();") (println) (println "  /* Test basic arithmetic */") (println "  oop result1= test_add(newLong(5), newLong(3));") (println "  printf(\"5 + 3 = %ld\\n\", getLong(result1));") (println) (println "  /* Test pair creation with GC protection */") (println "  oop result2= test_pair_creation(newLong(42), newLong(17));") (println "  printf(\"Pair: (%ld . %ld)\\n\", getLong(get(result2, Pair,head)), getLong(get(result2, Pair,tail)));") (println) (println "  /* Test string allocation */") (println "  oop result3= test_string_creation(newLong(10));") (println "  printf(\"Created string of length: %ld\\n\", getLong(get(result3, String,size)));") (println) (println "  /* Force GC to test our generated objects survive */") (println "  GC_gcollect();") (println "  printf(\"GC completed - objects still accessible\\n\");") (println) (println "  return 0;") (println "}") (println))
[?7h[32m[?7ltest-gc-c-emitter.l:65[0m (test-gc-emitter)
[?7h