. => ()
. => ()
./* Generated by Maru C backend */
 => "/* Generated by Maru C backend */"
.#include <stdio.h>
 => "#include <stdio.h>"
.#include <stdlib.h>
 => "#include <stdlib.h>"
.#include <string.h>
 => "#include <string.h>"
.
 => ()
.typedef union Object *oop;
 => "typedef union Object *oop;"
.#define nil ((oop)0)
 => "#define nil ((oop)0)"
.#define LONG(n) ((oop)(((long)(n) << 1) | 1))
 => "#define LONG(n) ((oop)(((long)(n) << 1) | 1))"
.#define getLong(x) ((long)(x) >> 1)
 => "#define getLong(x) ((long)(x) >> 1)"
.
 => ()
.int main() {
 => "int main() {"
.  oop _acc = nil;
 => "  oop _acc = nil;"
._acc = LONG(21);
 => "_acc = LONG("
.
emit: illegal instruction: (ADD 21)
[31;1merror: aborted[m
[32m[?7lboot.l:24   [0m (abort)
[?7h[32m[?7lemit.l:70   [0m (error "aborted")
[?7h[32m[?7lboot.l:707  [0m (apply default arguments)
[?7h[32m[?7lboot.l:706  [0m (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments))
[?7h[32m[?7lboot.l:705  [0m (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments)))
[?7h[32m[?7lboot.l:703  [0m (Fixed<if> (Fixed<and> method (not (array? method))) (apply method arguments) (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments))))
[?7h[32m[?7lboot.l:698  [0m (Fixed<let> ((method (oop-at (%typecheck <generic> self) 1)) (arg arguments)) (Fixed<while> arg (Fixed<set> method (array-at method (type-of (car arg)))) (Fixed<set> arg (cdr arg))) (Fixed<if> (Fixed<and> method (not (array? method))) (apply method arguments) (Fixed<let> ((default (oop-at (%typecheck <generic> self) 2))) (Fixed<if> default (apply default arguments) (error "no method in " (oop-at (%typecheck <generic> self) 0) " corresponding to " arguments)))))
[?7h[32m[?7l<stdin>:24  [0m (emit ADD (LI32 21))
[?7h