/* Threaded C Code Generated by Maru */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef void *oop;
#define nil ((oop)0)
#define LONG(n) ((oop)(((long)(n) << 1) | 1))
#define getLong(x) ((long)(x) >> 1)

typedef struct {
    oop stack[1024];    /* Value stack */
    oop *sp;            /* Stack pointer */
    oop locals[256];    /* Local variables */
    oop acc;            /* Accumulator */
} thread_context;

/* Runtime support functions */
oop lookup_var(const char *name, thread_context *ctx) {
    /* Variable lookup not implemented yet */
    return nil;
}

/* Forward declarations */
oop thread_1(thread_context *ctx);
oop thread_2(thread_context *ctx);
oop thread_3(thread_context *ctx);
oop thread_4(thread_context *ctx);
oop thread_5(thread_context *ctx);
oop thread_6(thread_context *ctx);

/* Thread implementations */
oop thread_1(thread_context *ctx) {
    return ctx->acc;
}

oop thread_2(thread_context *ctx) {
    return ctx->acc;
}

oop thread_3(thread_context *ctx) {
    ctx->acc = LONG(42);
    return thread_2(ctx);
}

oop thread_4(thread_context *ctx) {
    ctx->acc = LONG(0);
    return thread_2(ctx);
}

oop thread_5(thread_context *ctx) {
    ctx->acc = LONG(1);
    return dummy(ctx);
}

oop thread_6(thread_context *ctx) {
    oop test = thread_5(ctx);
    if (test && test != nil) {
        return thread_3(ctx);
    } else {
        return thread_4(ctx);
    }
}

int main() {
    thread_context ctx = {0};
    ctx.sp = ctx.stack;
    oop result = thread_6(&ctx);
    if (result) {
        printf("Result: %ld\n", getLong(result));
    } else {
        printf("Result: nil\n");
    }
    return 0;
}
